export enum HealthGoal {
  WEIGHT_LOSS = 'WEIGHT_LOSS',
  WEIGHT_GAIN = 'WEIGHT_GAIN',
  MAINTENANCE = 'MAINTENANCE',
  MUSCLE_GAIN = 'MUSCLE_GAIN',
  GENERAL_HEALTH = 'GENERAL_HEALTH',
  MANAGE_CONDITION = 'MANAGE_CONDITION',
}
