export enum MealTag {
  VEGETARIAN = 'VEGETARIAN',
  VEGAN = 'VEGAN',
  GLUTEN_FREE = 'GLUTEN_FREE',
  DAIRY_FREE = 'DAIRY_FREE',
  LOW_CARB = 'LOW_CARB',
  DIABETIC_FRIENDLY = 'DIABETIC_FRIENDLY',
  HEART_HEALTHY = 'HEART_HEALTHY',
  LOW_SODIUM = 'LOW_SODIUM',
  HIGH_PROTEIN = 'HIGH_PROTEIN',
  NUT_FREE = 'NUT_FREE',
}
